### ISSUE TITLE
TypeError: args.flatMap is not a function 

### ISSUE THREAD

**Issue by paratz** [darekkay/static-marks#27]
Hello Everyone, I'm trying to build my file and I receive the following error:

kmarks$ static-marks build demo.yml > bookmarks2.html
/usr/local/lib/node_modules/static-marks/bin/build/index.js:9
    .flatMap((file) => glob.sync(file, { realpath: true }))
     ^

TypeError: args.flatMap is not a function
    at Object.build [as run] (/usr/local/lib/node_modules/static-marks/bin/build/index.js:9:6)
    at Command.program.command.description.option.option.option.action (/usr/local/lib/node_modules/static-marks/bin/cli.js:23:38)
    at Command.listener (/usr/local/lib/node_modules/static-marks/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/usr/local/lib/node_modules/static-marks/node_modules/commander/index.js:892:12)
    at Command.parse (/usr/local/lib/node_modules/static-marks/node_modules/commander/index.js:642:21)
    at cli (/usr/local/lib/node_modules/static-marks/bin/cli.js:59:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/static-marks/bin/static-marks.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

I'm using the Ubuntu 20.04, and I got the same error in the Docker setup.
I'm using the demofiles from https://github.com/darekkay/static-marks/tree/master/docs/examples/bookmarks

Any idea what can cause this? Thanks in advanced,

**Comment by darekkay** [comment]
Hi @paratz , which Node version are you using? `flatMap` [requires](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#browser_compatibility) at least Node v11.0.0. However, Node versions below v12.0.0 are [officially deprecated/unmaintained](https://nodejs.org/en/about/releases/). Static Marks follows the official release timeline and hence only works with Node 12+.

The (unofficial) Docker image still [uses Node 10](https://github.com/gaerfield/static-marks-docker/blob/master/Dockerfile#L1) as well, but I will create a PR to have this fixed.

**Comment by paratz** [comment]
Thanks for your reply…. You are right, I was using node v10.19.0… just upgraded using these instructions<https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version> and everything was ok…

It would be great if the docker image is updated…

Excellent tool!

**Comment by darekkay** [comment]
Great to hear that it's working now :)

Docker image PR is open: https://github.com/gaerfield/static-marks-docker/pull/1
